# Configuration
PREFIX ?= ~/openexrid
EXR_INCLUDE ?= /usr/include/OpenEXR
EXR_LIB ?= /usr/lib
OFX_INCLUDE ?= /usr/include/OpenEXR
RE2_INCLUDE ?= /usr/include/

VERSION ?= release
CPPFLAGS += -std=c++11 -O3 -Wall -DNDEBUG -fPIC -I $(EXR_INCLUDE) -I $(OFX_INCLUDE) -I $(RE2_INCLUDE) -Dlinux
LDFLAGS += -static-libstdc++ -static-libgcc -L$(EXR_LIB) -L../openexrid/$(VERSION) -lpthread
LDFLAGS += -Wl,-Bstatic -lopenexrid -lIlmImf -lIlmThread -lIex -lImath -lHalf -lz -lre2
