
# Configuration
# All variables can be overriden in the makefile.myconfig next to this file

PREFIX ?= ~/openexrid

OFX_INCLUDE ?= /usr/include/openfx
EXR_INCLUDE ?= /usr/include/OpenEXR
EXR_LIB ?= /usr/lib
RE2_INCLUDE ?= /usr/include
RE2_LIB ?= /usr/lib

VERSION ?= release
CPPFLAGS += -O3 -Wall -DNDEBUG -fPIC -I $(EXR_INCLUDE) -I $(OFX_INCLUDE) -I $(RE2_INCLUDE) -Dlinux
LDFLAGS += -L$(EXR_LIB) -L$(RE2_LIB) -L../openexrid/$(VERSION) -lpthread
LDFLAGS += -Wl,-Bstatic -lopenexrid -lIlmImf -lIlmThread -lIex -lImath -lHalf -lz -lre2 -Wl,-Bdynamic

